# Generated by Django 5.2.17 on 2026-08-29 20:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_type', models.CharField(choices=[('TASK', 'Task Campaign'), ('ADVERTISEMENT', 'Advertisement Campaign'), ('SPONSORED_CONTENT', 'Sponsored Content Campaign')], db_index=True, default='TASK', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=30)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_campaign_status'), models.Index(fields=['campaign_type'], name='idx_campaign_type'), models.Index(fields=['owner', 'status'], name='idx_campaign_owner_status'), models.Index(fields=['status', 'campaign_type'], name='idx_campaign_status_type')],
            },
        ),
    ]
