# Generated by Django 5.2.17 on 2026-08-29 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('VIDEO', 'Video Asset'), ('IMAGE', 'Image Asset'), ('BANNER', 'Banner Asset')], db_index=True, default='IMAGE', max_length=20)),
                ('file', models.FileField(upload_to='campaign_media/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='campaign_media/thumbnails/%Y/%m/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duration in seconds for video assets', null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('DISABLED', 'Disabled')], db_index=True, default='READY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='campaigns.campaign')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_campaign_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Media',
                'verbose_name_plural': 'Campaign Media Assets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign'], name='idx_media_campaign'), models.Index(fields=['media_type'], name='idx_media_type'), models.Index(fields=['status'], name='idx_media_status'), models.Index(fields=['uploaded_by'], name='idx_media_uploader'), models.Index(fields=['campaign', 'status'], name='idx_media_camp_status')],
            },
        ),
    ]
