# Generated by Django 5.2.17 on 2026-08-30 11:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignmedia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignAdPlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placement_type', models.CharField(choices=[('HOME_FEED', 'Home Feed'), ('HEADER', 'Header Banner'), ('FOOTER', 'Footer Banner'), ('POPUP', 'Popup Advertisement'), ('VIDEO_PREROLL', 'Video Pre-roll'), ('TASK_FEED', 'Task Feed Section')], db_index=True, default='HOME_FEED', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DISABLED', 'Disabled')], db_index=True, default='DRAFT', max_length=20)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Delivery priority weight (higher integer = served first)')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ad_placements', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='campaigns.campaignmedia')),
            ],
            options={
                'verbose_name': 'Advertisement Placement',
                'verbose_name_plural': 'Advertisement Placements',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['placement_type'], name='idx_place_type'), models.Index(fields=['status'], name='idx_place_status'), models.Index(fields=['campaign'], name='idx_place_campaign'), models.Index(fields=['media'], name='idx_place_media'), models.Index(fields=['placement_type', 'status'], name='idx_place_type_status'), models.Index(fields=['campaign', 'status'], name='idx_place_camp_status')],
            },
        ),
    ]
