# Generated by Django 5.2.17 on 2026-08-30 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaignadplacement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementImpression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to='campaigns.campaign')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to='campaigns.campaignmedia')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to='campaigns.campaignadplacement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertisement Impression',
                'verbose_name_plural': 'Advertisement Impressions',
                'db_table': 'campaign_ad_impressions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('click_type', models.CharField(choices=[('BANNER_CLICK', 'Banner Click'), ('VIDEO_CLICK', 'Video Click'), ('CALL_ACTION', 'Call to Action'), ('EXTERNAL_LINK', 'External Link')], db_index=True, default='BANNER_CLICK', max_length=32)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_clicks', to='campaigns.campaign')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_clicks', to='campaigns.campaignmedia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_clicks', to=settings.AUTH_USER_MODEL)),
                ('impression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_clicks', to='campaigns.advertisementimpression')),
            ],
            options={
                'verbose_name': 'Advertisement Click',
                'verbose_name_plural': 'Advertisement Clicks',
                'db_table': 'campaign_ad_clicks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementVideoEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('watched_seconds', models.FloatField(default=0.0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_video_engagements', to='campaigns.campaign')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_video_engagements', to='campaigns.campaignmedia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_video_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Ad Engagement',
                'verbose_name_plural': 'Video Ad Engagements',
                'db_table': 'campaign_ad_video_engagements',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='advertisementimpression',
            index=models.Index(fields=['campaign', 'created_at'], name='idx_ad_imp_camp_time'),
        ),
        migrations.AddIndex(
            model_name='advertisementimpression',
            index=models.Index(fields=['placement', 'created_at'], name='idx_ad_imp_place_time'),
        ),
        migrations.AddIndex(
            model_name='advertisementimpression',
            index=models.Index(fields=['media', 'created_at'], name='idx_ad_imp_media_time'),
        ),
        migrations.AddIndex(
            model_name='advertisementimpression',
            index=models.Index(fields=['user', 'created_at'], name='idx_ad_imp_user_time'),
        ),
        migrations.AddIndex(
            model_name='advertisementimpression',
            index=models.Index(fields=['session_id', 'created_at'], name='idx_ad_imp_sess_time'),
        ),
        migrations.AddIndex(
            model_name='advertisementclick',
            index=models.Index(fields=['campaign', 'created_at'], name='idx_ad_clk_camp_time'),
        ),
        migrations.AddIndex(
            model_name='advertisementclick',
            index=models.Index(fields=['media', 'created_at'], name='idx_ad_clk_media_time'),
        ),
        migrations.AddIndex(
            model_name='advertisementclick',
            index=models.Index(fields=['click_type', 'created_at'], name='idx_ad_clk_type_time'),
        ),
        migrations.AddIndex(
            model_name='advertisementvideoengagement',
            index=models.Index(fields=['campaign', 'created_at'], name='idx_ad_vid_camp_time'),
        ),
        migrations.AddIndex(
            model_name='advertisementvideoengagement',
            index=models.Index(fields=['media', 'created_at'], name='idx_ad_vid_media_time'),
        ),
        migrations.AddIndex(
            model_name='advertisementvideoengagement',
            index=models.Index(fields=['session_id'], name='idx_ad_vid_session'),
        ),
        migrations.AddIndex(
            model_name='advertisementvideoengagement',
            index=models.Index(fields=['completed'], name='idx_ad_vid_completed'),
        ),
    ]
