# Generated by Django 5.2.17 on 2026-08-26 12:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('INVALID', 'Invalid'), ('EXPIRED', 'Expired'), ('ABANDONED', 'Abandoned')], db_index=True, default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('required_seconds', models.PositiveIntegerField(default=60)),
                ('credited_watch_seconds', models.PositiveIntegerField(default=0)),
                ('heartbeat_count', models.PositiveIntegerField(default=0)),
                ('invalid_event_count', models.PositiveIntegerField(default=0)),
                ('client_platform', models.CharField(default='MOBILE', max_length=50)),
                ('app_version', models.CharField(default='1.0.0', max_length=50)),
                ('device_id_hash', models.CharField(blank=True, max_length=64)),
                ('client_session_id', models.CharField(blank=True, max_length=100)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
                ('last_client_position', models.FloatField(blank=True, null=True)),
                ('is_backgrounded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_session', to='tasks.taskattempt')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_sessions', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vewra_watch_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('SESSION_STARTED', 'Session Started'), ('PLAY', 'Play'), ('PAUSE', 'Pause'), ('HEARTBEAT', 'Heartbeat'), ('APP_BACKGROUND', 'App Background'), ('APP_FOREGROUND', 'App Foreground'), ('VISIBILITY_LOST', 'Visibility Lost'), ('VISIBILITY_RESTORED', 'Visibility Restored'), ('PLAYER_ENDED', 'Player Ended'), ('QUIZ_STARTED', 'Quiz Started'), ('QUIZ_SUBMITTED', 'Quiz Submitted'), ('SESSION_COMPLETED', 'Session Completed'), ('SESSION_INVALIDATED', 'Session Invalidated')], max_length=30)),
                ('sequence', models.PositiveIntegerField()),
                ('client_timestamp', models.DateTimeField(blank=True, null=True)),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('playback_position', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.watchsession')),
            ],
            options={
                'db_table': 'vewra_watch_events',
                'ordering': ['server_timestamp', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='watchsession',
            index=models.Index(fields=['user', 'status'], name='vewra_watch_user_id_13b676_idx'),
        ),
        migrations.AddIndex(
            model_name='watchsession',
            index=models.Index(fields=['session_token_hash'], name='vewra_watch_session_15ca1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='watchevent',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='unique_session_sequence'),
        ),
    ]
