# Generated by Django 5.2.17 on 2026-08-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchevent',
            options={'ordering': ['server_timestamp', 'sequence'], 'verbose_name': 'Watch Heartbeat Event', 'verbose_name_plural': 'Watch Heartbeat Events'},
        ),
        migrations.AlterModelOptions(
            name='watchsession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Watch Session', 'verbose_name_plural': 'Watch Sessions'},
        ),
        migrations.RemoveConstraint(
            model_name='watchevent',
            name='unique_session_sequence',
        ),
    ]
