# Generated by Django 5.2.17 on 2026-08-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('platform', models.CharField(default='android', max_length=50)),
                ('app_version', models.CharField(default='1.0.0', max_length=20)),
                ('is_trusted', models.BooleanField(default=True)),
                ('is_vpn_detected', models.BooleanField(default=False)),
                ('is_rooted', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Device Security',
                'verbose_name_plural': 'Device Securities',
                'db_table': 'vewra_device_security',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_level', models.CharField(choices=[('BASIC', 'Basic User'), ('VERIFIED', 'Verified User'), ('TRUSTED', 'Trusted User')], default='BASIC', max_length=20)),
                ('document_status', models.CharField(choices=[('BASIC', 'Basic'), ('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='BASIC', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Verification',
                'verbose_name_plural': 'Verifications',
                'db_table': 'vewra_verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
