# Generated by Django 5.2.17 on 2026-08-25 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='country',
            field=models.CharField(default='Global', max_length=100),
        ),
        migrations.AddField(
            model_name='verification',
            name='document_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='verification',
            name='document_type',
            field=models.CharField(choices=[('NATIONAL_ID', 'National ID Card'), ('PASSPORT', 'International Passport'), ('DRIVERS_LICENSE', "Driver's License"), ('UTILITY_BILL', 'Utility Bill'), ('OTHER', 'Other Official ID')], default='NATIONAL_ID', max_length=30),
        ),
        migrations.AddField(
            model_name='verification',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='verification',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='document_status',
            field=models.CharField(default='BASIC', max_length=20),
        ),
        migrations.CreateModel(
            name='TrustScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_score', models.PositiveIntegerField()),
                ('new_score', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trust Score History',
                'verbose_name_plural': 'Trust Score Histories',
                'db_table': 'vewra_trust_score_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
