# Generated by Django 5.2.17 on 2026-08-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(default='OpenRouter', max_length=50)),
                ('api_key', models.CharField(blank=True, help_text='OpenRouter API Key (e.g. sk-or-v1-...)', max_length=255)),
                ('base_url', models.CharField(default='https://openrouter.ai/api/v1', help_text='API Endpoint base URL', max_length=255)),
                ('youtube_keyword_model', models.CharField(default='google/gemini-2.0-flash-001', help_text='Dynamically fetched OpenRouter model for YouTube transcript & keyword generation', max_length=150)),
                ('quiz_generation_model', models.CharField(default='openai/gpt-4o-mini', help_text='Dynamically fetched OpenRouter model for task quiz questions', max_length=150)),
                ('fraud_analysis_model', models.CharField(default='anthropic/claude-3.5-haiku', help_text='Dynamically fetched OpenRouter model for anti-fraud analysis', max_length=150)),
                ('cached_models', models.JSONField(blank=True, default=list, help_text='Cached list of available models fetched dynamically from OpenRouter API')),
                ('last_models_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('site_url', models.CharField(default='https://vewra.com', help_text='HTTP-Referer header for OpenRouter', max_length=200)),
                ('site_name', models.CharField(default='Vewra Platform', help_text='X-Title header for OpenRouter', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Enable OpenRouter AI features')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OpenRouter AI Provider & Model Config',
                'verbose_name_plural': 'OpenRouter AI Provider & Model Configs',
                'db_table': 'vewra_ai_provider_config',
            },
        ),
    ]
