# Generated by Django 5.2.17 on 2026-08-25 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('CONVERSION', 'Conversion'), ('REWARD', 'Reward'), ('PURCHASE', 'Purchase'), ('ADJUSTMENT', 'Adjustment')], default='REWARD', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reference', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Transaction',
                'verbose_name_plural': 'Cash Transactions',
                'db_table': 'vewra_cash_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('REWARD', 'Reward'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('PROMOTION', 'Promotion'), ('BONUS', 'Bonus'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer'), ('WITHDRAWAL', 'Withdrawal')], default='REWARD', max_length=20)),
                ('amount', models.BigIntegerField(help_text='Positive for credit, negative for debit')),
                ('balance_before', models.PositiveBigIntegerField()),
                ('balance_after', models.PositiveBigIntegerField()),
                ('reference', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coin Transaction',
                'verbose_name_plural': 'Coin Transactions',
                'db_table': 'vewra_coin_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reference', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit Record',
                'verbose_name_plural': 'Deposit Records',
                'db_table': 'vewra_deposit_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_balance', models.PositiveBigIntegerField(default=0)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pending_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pending_coins', models.PositiveIntegerField(default=0)),
                ('lifetime_coins', models.PositiveBigIntegerField(default=0)),
                ('lifetime_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Wallet',
                'verbose_name_plural': 'User Wallets',
                'db_table': 'vewra_wallets',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coins_deducted', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('method', models.CharField(choices=[('BANK', 'Direct Bank Wire'), ('CRYPTO', 'Cryptocurrency'), ('USDT', 'USDT (TRC-20 / BEP-20)'), ('GIFTCARD', 'Digital Gift Card'), ('PAYPAL', 'PayPal Transfer')], default='USDT', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('destination', models.CharField(help_text='Recipient wallet address, IBAN, account number or PayPal email', max_length=255)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'db_table': 'vewra_withdrawal_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
