# Generated by Django 5.2.17 on 2026-08-26 12:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice')], default='MULTIPLE_CHOICE', max_length=20)),
                ('options', models.JSONField(default=list, help_text="List of answer options e.g. ['A', 'B', 'C', 'D']")),
                ('correct_answer', models.CharField(help_text='Server-only correct answer string', max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('source_timestamp_seconds', models.PositiveIntegerField(blank=True, help_text='Video timestamp for reference', null=True)),
                ('difficulty', models.CharField(default='MEDIUM', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vewra_quiz_questions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('pass_percentage', models.PositiveIntegerField(default=70)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vewra_quiz_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('selected_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tasks.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='tasks.quizquestion')),
            ],
            options={
                'db_table': 'vewra_quiz_answers',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('VIDEO', 'Video'), ('SURVEY', 'Survey'), ('SOCIAL', 'Social'), ('CHALLENGE', 'Challenge')], db_index=True, default='VIDEO', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('EXHAUSTED', 'Exhausted'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.JSONField(blank=True, default=list, help_text='List of string steps for the user')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('source_url', models.URLField(max_length=500)),
                ('source_platform', models.CharField(default='YouTube', max_length=50)),
                ('channel_name', models.CharField(blank=True, max_length=150)),
                ('search_keywords', models.TextField(blank=True)),
                ('reward_coins', models.PositiveBigIntegerField(default=10)),
                ('reward_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reward_xp', models.PositiveIntegerField(default=25)),
                ('required_watch_seconds', models.PositiveIntegerField(default=60)),
                ('quiz_required', models.BooleanField(default=False)),
                ('quiz_pass_percentage', models.PositiveIntegerField(default=70)),
                ('daily_user_limit', models.PositiveIntegerField(default=1, help_text='Max completions per user per day')),
                ('total_completion_limit', models.PositiveIntegerField(blank=True, help_text='Global campaign capacity', null=True)),
                ('total_completions', models.PositiveIntegerField(default=0)),
                ('minimum_level', models.PositiveIntegerField(default=1)),
                ('minimum_trust_score', models.PositiveIntegerField(default=50)),
                ('verification_required', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vewra_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='tasks.task'),
        ),
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_QUIZ', 'Awaiting Quiz'), ('VERIFYING', 'Verifying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ABANDONED', 'Abandoned')], db_index=True, default='CREATED', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('reward_granted', models.BooleanField(default=False)),
                ('reward_granted_at', models.DateTimeField(blank=True, null=True)),
                ('reward_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('quiz_required', models.BooleanField(default=False)),
                ('quiz_passed', models.BooleanField(blank=True, null=True)),
                ('quiz_score', models.FloatField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vewra_task_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='task_attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempt', to='tasks.taskattempt'),
        ),
        migrations.CreateModel(
            name='TaskRewardGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coins', models.PositiveBigIntegerField(default=0)),
                ('cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('wallet_reference', models.CharField(max_length=100, unique=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_grant', to='tasks.taskattempt')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_grants', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reward_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vewra_task_reward_grants',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'task_type'], name='vewra_tasks_status_0434b8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['starts_at', 'expires_at'], name='vewra_tasks_starts__c55d82_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(fields=['user', 'task', 'status'], name='vewra_task__user_id_0633d9_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(fields=['started_at'], name='vewra_task__started_4eb9b3_idx'),
        ),
    ]
