# Generated by Django 5.2.17 on 2026-08-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='reward_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='task',
            name='reward_type',
            field=models.CharField(choices=[('per_time', 'Per Time'), ('watch_all', 'Watch All'), ('target', 'Target')], default='target', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='video_id',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
