# Generated by Django 5.2.17 on 2026-08-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_keywords_task_reward_config_task_reward_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(default='OpenRouter', max_length=50)),
                ('api_key', models.CharField(blank=True, help_text='OpenRouter API Key (e.g. sk-or-v1-...)', max_length=255)),
                ('base_url', models.CharField(default='https://openrouter.ai/api/v1', help_text='API Endpoint base URL', max_length=255)),
                ('youtube_keyword_model', models.CharField(default='google/gemini-2.0-flash-001', help_text='Model for YouTube transcript analysis and top-ranking search keyword generation', max_length=100)),
                ('quiz_generation_model', models.CharField(default='openai/gpt-4o-mini', help_text='Model for generating task verification quiz questions', max_length=100)),
                ('fraud_analysis_model', models.CharField(default='anthropic/claude-3.5-haiku', help_text='Model for evaluating anomalous watch patterns and fraud detection', max_length=100)),
                ('site_url', models.CharField(default='https://vewra.com', help_text='HTTP-Referer header for OpenRouter', max_length=200)),
                ('site_name', models.CharField(default='Vewra Platform', help_text='X-Title header for OpenRouter', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Enable OpenRouter AI features')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OpenRouter AI Provider & Model Config',
                'verbose_name_plural': 'OpenRouter AI Provider & Model Configs',
                'db_table': 'vewra_ai_provider_config',
            },
        ),
        migrations.AlterModelOptions(
            name='quizanswer',
            options={'ordering': ['created_at'], 'verbose_name': 'Quiz Answer', 'verbose_name_plural': 'Quiz Answers'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Quiz Verification Attempt', 'verbose_name_plural': 'Quiz Verification Attempts'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['created_at'], 'verbose_name': 'Quiz Question', 'verbose_name_plural': 'Quiz Questions'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'YouTube Video Task', 'verbose_name_plural': 'YouTube Video Tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Task Completion Attempt', 'verbose_name_plural': 'Task Completion Attempts'},
        ),
        migrations.AlterModelOptions(
            name='taskrewardgrant',
            options={'ordering': ['-granted_at'], 'verbose_name': 'Task Reward Grant', 'verbose_name_plural': 'Task Reward Grants'},
        ),
        migrations.AlterField(
            model_name='taskattempt',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_QUIZ', 'Awaiting Quiz'), ('VERIFYING', 'Verifying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('ABANDONED', 'Abandoned')], db_index=True, default='CREATED', max_length=20),
        ),
    ]
