# Generated by Django 5.2.17 on 2026-08-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_aiproviderconfig_alter_quizanswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproviderconfig',
            name='cached_models',
            field=models.JSONField(blank=True, default=list, help_text='Cached list of available models fetched dynamically from OpenRouter API'),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='last_models_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='fraud_analysis_model',
            field=models.CharField(default='anthropic/claude-3.5-haiku', help_text='Dynamically fetched OpenRouter model for anti-fraud analysis', max_length=150),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='quiz_generation_model',
            field=models.CharField(default='openai/gpt-4o-mini', help_text='Dynamically fetched OpenRouter model for task quiz questions', max_length=150),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='youtube_keyword_model',
            field=models.CharField(default='google/gemini-2.0-flash-001', help_text='Dynamically fetched OpenRouter model for YouTube transcript & keyword generation', max_length=150),
        ),
    ]
