# Generated by Django 5.2.17 on 2026-08-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_aiproviderconfig_cached_models_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIProviderConfig',
        ),
    ]
