# Generated by Django 5.2.17 on 2026-08-30 14:43

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0004_advertisementimpression_advertisementclick_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('IMPRESSION', 'Impression (CPM)'), ('CLICK', 'Click (CPC)'), ('VIDEO_COMPLETION', 'Video Completion (CPV)'), ('CONVERSION', 'Conversion Action')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('reference_id', models.CharField(db_index=True, help_text='ID of the tracked impression, click, or engagement', max_length=255)),
                ('fraud_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_charges', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_charges', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Advertisement Charge',
                'verbose_name_plural': 'Advertisement Charges',
                'db_table': 'advertising_charges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['advertiser', 'created_at'], name='advertising_adverti_707177_idx'), models.Index(fields=['campaign', 'created_at'], name='advertising_campaig_2d3427_idx'), models.Index(fields=['event_type', 'created_at'], name='advertising_event_t_694811_idx'), models.Index(fields=['reference_id'], name='advertising_referen_6aa053_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementFraudLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('IMPRESSION', 'Impression (CPM)'), ('CLICK', 'Click (CPC)'), ('VIDEO_COMPLETION', 'Video Completion (CPV)'), ('CONVERSION', 'Conversion Action')], max_length=30)),
                ('fraud_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk / Blocked')], db_index=True, default='LOW', max_length=20)),
                ('flag_reason', models.CharField(max_length=255)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('session_id', models.CharField(blank=True, default='', max_length=128)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertising_fraud_logs', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_logs', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Fraud Log',
                'verbose_name_plural': 'Fraud Logs',
                'db_table': 'advertising_fraud_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'risk_level'], name='advertising_campaig_9869b6_idx'), models.Index(fields=['risk_level', 'created_at'], name='advertising_risk_le_6c4923_idx'), models.Index(fields=['ip_hash', 'created_at'], name='advertising_ip_hash_ed2644_idx'), models.Index(fields=['session_id', 'created_at'], name='advertising_session_c26412_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdvertiserWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('total_spent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertiser Wallet',
                'verbose_name_plural': 'Advertiser Wallets',
                'db_table': 'advertising_advertiser_wallets',
                'indexes': [models.Index(fields=['advertiser', 'created_at'], name='advertising_adverti_71ed7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CampaignBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('spent_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('daily_spent_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('last_spend_date', models.DateField(blank=True, null=True)),
                ('cpm_rate', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Cost per 1000 impressions in USD', max_digits=8)),
                ('cpc_rate', models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Cost per verified click in USD', max_digits=8)),
                ('cpv_rate', models.DecimalField(decimal_places=2, default=Decimal('0.05'), help_text='Cost per video completion (>=95%) in USD', max_digits=8)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('EXHAUSTED', 'Budget Exhausted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_config', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Budget',
                'verbose_name_plural': 'Campaign Budgets',
                'db_table': 'advertising_campaign_budgets',
                'indexes': [models.Index(fields=['campaign', 'status'], name='advertising_campaig_fb88fc_idx'), models.Index(fields=['status', 'created_at'], name='advertising_status_a109ca_idx')],
            },
        ),
    ]
